### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [rasenderhase/codecademy#4]
Grade: Exceeds Expectations

Summary:
Andreas, congrats on finishing your capstone project! You did an excellent job overall both visually and code wise. On the visual side I enjoyed the hover effects you added they were subtle yet the response they provided to hover actions was perfect! Your site was also responsive as it adapted nicely to the various widths I tested it in. 

Code wise you did an excellent job following conventions, making use of roles, aria-labels, [character entity references](https://developer.mozilla.org/en-US/docs/Glossary/Entity), and structuring your HTML and CSS code. The only area I felt your project could improve on was making use of the alt attribute as mentioned in issue number #2 as I didn't see being used. 

To expand on your project consider making use of [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) in your stylesheet as they're a great tool for increasing the readability of your files and making them easier to manage.

**Comment by rasenderhase** [comment]
Hi @jim-rosales ,
thanks for the helpful feedback.
For the „alt“-attributes: I‘ll do better in future 😇
I also like these CSS variables. MDN states that they are not supported in IE. Is it a good idea to use them, though? Will support for them be added in IE soon?
Best regards 
Andy

**Comment by jim-rosales** [comment]
Hi @rasenderhase,

Unfortunately, it doesn't look like support will be added for IE since IE is being supported any more development wise. The only updates it is receiving are UI changes and security updates from now on since Microsoft if pushing more Edge support. 

In this case, if a project you are working on needs to support IE then it seems like making use of variables won't be a great option. You can use Sass in this case, since all Sass needs is a compiler to convert it to CSS. Codecaemy does offer a lesson in Sass which I do reccomend you take if you want to learn more about.

**Comment by rasenderhase** [comment]
Thanks again for clarification. I forgot about Edge... Hope my customers will move to Edge (or Chrome, Firefox...) soon.
